### ISSUE TITLE
test: add assertion for a multiple claim on the same deal

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/smart-contract#10]
Add this assertion: `Should give the amount of the first claimer who claim in multiple successful claims`.

Create a scenario with 2 claimers, then the first claimer will get the reward.

**Comment by n1c01a5** [comment]
create this $test for 30XDAI (XDAI)

**Comment by Opixelum** [comment]
#11

**Comment by n1c01a5** [comment]
@Opixelum you did only one `claim` and the test don't specify to to challenge it.

So add a new `claim` and remove any challenge else I will challenge you 😅

**Comment by Opixelum** [comment]
Oh okay, I think I get it 😃
