### ISSUE TITLE
$CI: add Github Action workflow to run the tests 30XDAI (xdai)

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/smart-contract#12]
See [Github Actions](https://docs.github.com/en/actions/learn-github-actions) .

**Comment by Opixelum** [comment]
feat #13

**Comment by n1c01a5** [comment]
@Opixelum looks good but can you ignore the `test/feature-erc20.js` because it's out of the scope of this issue.

In another issue, we can set a prettier file with  the code format.

**Comment by Opixelum** [comment]
I removed the feature-erc20 test.

There is a prettierrc file already in this repo. You want to update it in another issue?

**Comment by n1c01a5** [comment]
Done with https://github.com/feature-sh/smart-contract/pull/15 .

**Comment by Opixelum** [comment]
Payment executed.
