### ISSUE TITLE
Fix: deployments of version 2.1.0 of Feature and FeatureERC20 smart contracts

### ISSUE THREAD

**Issue by BLOCKCHAINDEVWEB** [feature-sh/smart-contract#33]
See the modifications of smart contracts: 
- https://github.com/feature-sh/smart-contract/pull/32
See the modifications of Monitor:
- https://github.com/feature-sh/monitor/pull/314
See the modifications of Monitor-blocks:
- https://github.com/feature-sh/monitor-block/commit/689bd9d939260fbfad1ea90e39aa54f0c066f7a1

# Mainnet
- [x] Update on the Gnosis Chain.
- [x] Update on the Polygon.
- [ ] Update on the Arbitrum One.
- [ ] Update Dune Analytics for Gnosis Chain.

# Testnet
- [x] Update on the Goerli.
- [x] Update on the Mumbai.

# Bot
- [ ] Update all production environment variables on Testnet networks.
- [ ] Update all development environment variables on Mainnet networks.

# Monitors v2 or  Monitors-block
- [ ] Update all production environment variables on Testnet networks.
- [ ] Update all development environment variables on Mainnet networks.

**Comment by n1c01a5** [comment]
See https://github.com/feature-sh/smart-contract/issues/37
