### ISSUE TITLE
Deploy smart contract version `2.4.1`

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/smart-contract#37]
## Changes

- #36 

## Mainnets

- [x] Gnosis chain
- [x] Polygon
- ~~[ ] Arbitrum~~
- [x] Celo
- [x] Binance

## Testnets

- ~~[ ] Goerli~~
- [x] Sepolia
- [x] Mumbai
- [x] Alfajores

## Mainnets (dev mode)

- [x] Gnosis chain
- [x] Polygon
- ~~[ ] Arbitrum~~
- [x] Celo
- [x] Binance

**Comment by BLOCKCHAINDEVWEB** [comment]
Smart-contract Feature version for the Deal is v2.1.0. After completing the tasks for v2.4.1, I can no longer Claim (v2.1.0) and receive my reward (v2.1.0).

**Comment by n1c01a5** [comment]
> Smart-contract Feature version for the Deal is v2.1.0. After completing the tasks for v2.4.1, I can no longer Claim (v2.1.0) and receive my reward (v2.1.0).

Yep you can't do this from the FEATURE interface now but you can use https://gnosisscan.io/address/0x410f020aef826157ebe9c09fd2a7ef2a89bd6e34#writeContract .

**Comment by BLOCKCHAINDEVWEB** [comment]
This issue has been done.

I'm closing this issue.
