### ISSUE TITLE
refacto: clean indentation of the smart contracts

### ISSUE THREAD

**Issue by n1c01a5** [feature-sh/smart-contract#6]
By convention, the interval of solidity is 4 spaces.

See OpenZepplin smart contract as reference: [OZ](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol) .

**Comment by n1c01a5** [comment]
$bounty of 2000 FEAT (xdai)

**Comment by Opixelum** [comment]
#9
