### ISSUE TITLE
Change token ERC20Mock with FeatureToken

### ISSUE THREAD

**Issue by BLOCKCHAINDEVWEB** [feature-sh/smart-contract#7]
$feat with 500 FEAT rewards (xdai)

**Comment by BLOCKCHAINDEVWEB** [comment]
https://github.com/feature-sh/smart-contract/pull/8

**Comment by BLOCKCHAINDEVWEB** [comment]
#8

**Comment by n1c01a5** [comment]
It's better to get something generic like `ERC20Mock`.
